name: social_media_zego
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.3.0
  firebase_auth: ^5.1.4
  collection: ^1.18.0
  http_parser: ^4.0.2
  material_color_utilities: ^0.11.1
  string_scanner: ^1.2.0
  test_api: ^0.7.2
  web: ^0.5.1
   
  form_validator: ^2.1.1
    

dev_dependencies:
  flutter_test:
    sdk: flutter
   
  # Remove the test_api dependency

flutter:
  uses-material-design: true
